services:
  litespeed:
    build:
      context: ./lsws-build
      dockerfile: Dockerfile
    volumes:
      - ./lsws-conf:/usr/local/lsws/conf
      - ./vhost-localhost:/var/www/vhosts/localhost
    ports:
      - 80:80
      - 7080:7080
    networks:
      staging:
    restart: unless-stopped
    stop_signal: SIGKILL
    deploy:
      resources:
        limits:
          memory: 1G
  mariadb:
    image: mariadb
    environment:
      - MARIADB_USER=laravel
      - MARIADB_PASSWORD=password
      - MARIADB_DATABASE=attendance_api
      - MARIADB_RANDOM_ROOT_PASSWORD=yes
    expose:
      - "3306"
    networks:
      staging:
    restart: unless-stopped
networks:
  staging:
    driver: bridge
