#!/usr/bin/env bash

if [ ! -z "$WWWUSER" ]; then
    usermod -u $WWWUSER sail
fi

if [ ! -d /.composer ]; then
    mkdir /.composer
fi

chmod -R ugo+rw /.composer

gosu $WWWUSER bash << "EOF"

cd /var/www/html/attendance-api
composer install

if [ ! -f .env ]; then
    cp .env.example .env
    sed -i 's/\r//' .env
fi

source .env
if [ "${APP_KEY}" == '' ]; then
    /usr/bin/php artisan key:generate
fi

EOF

if [ $# -gt 0 ]; then
    exec gosu $WWWUSER "$@"
else
    exec /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
fi
