version: '3'
services:
  nginx:
    image: nginx:stable-alpine
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./data/conf.d:/etc/nginx/conf.d
    networks:
      sail:
networks:
  sail:
    external: true
    name: attendance
